In [258]:
# 导包
import torch
from torch.nn import functional as F
from torch import nn
from torch import optim
from torchvision import datasets, transforms
# import torchvision
from matplotlib import pyplot as plt
import import_ipynb

# 激活函数

## sigmoid

In [259]:
a = torch.linspace(-1, 1, 10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [260]:
torch.sigmoid(a)

tensor([0.2689, 0.3148, 0.3646, 0.4174, 0.4723, 0.5277, 0.5826, 0.6354, 0.6852,
        0.7311])

In [261]:
F.sigmoid(a)

tensor([0.2689, 0.3148, 0.3646, 0.4174, 0.4723, 0.5277, 0.5826, 0.6354, 0.6852,
        0.7311])

In [262]:
nn.Sigmoid().forward(a)

tensor([0.2689, 0.3148, 0.3646, 0.4174, 0.4723, 0.5277, 0.5826, 0.6354, 0.6852,
        0.7311])

## tanh

In [263]:
a = torch.linspace(-1, 1, 10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [264]:
torch.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

In [265]:
F.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

In [266]:
nn.Tanh().forward(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

## relu

In [267]:
a = torch.linspace(-1, 1, 10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [268]:
torch.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [269]:
F.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [270]:
nn.ReLU().forward(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

## leaky_relu

In [271]:
a = torch.linspace(-1, 1, 10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [272]:
F.leaky_relu(a)

tensor([-0.0100, -0.0078, -0.0056, -0.0033, -0.0011,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [273]:
nn.LeakyReLU().forward(a)

tensor([-0.0100, -0.0078, -0.0056, -0.0033, -0.0011,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

## softmax

In [274]:
a = torch.linspace(-1, 1, 10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [275]:
torch.softmax(a, dim=0)

tensor([0.0302, 0.0378, 0.0472, 0.0589, 0.0736, 0.0919, 0.1147, 0.1433, 0.1789,
        0.2235])

In [276]:
F.softmax(a, dim=0)

tensor([0.0302, 0.0378, 0.0472, 0.0589, 0.0736, 0.0919, 0.1147, 0.1433, 0.1789,
        0.2235])

In [277]:
nn.Softmax(dim=0).forward(a)

tensor([0.0302, 0.0378, 0.0472, 0.0589, 0.0736, 0.0919, 0.1147, 0.1433, 0.1789,
        0.2235])

# 计算损失

In [278]:
x = torch.randn(1, 784)
w = torch.randn(10, 784)

In [279]:
logits = x @ w.t()
logits

tensor([[ 19.3992,  35.2730,  36.3524,  19.2576, -15.0187, -14.3509,  52.9445,
          -8.9378,  39.2892,  12.7513]])

In [280]:
pred = F.softmax(logits, dim = 1)
pred

tensor([[2.7005e-15, 2.1153e-08, 6.2249e-08, 2.3439e-15, 3.0474e-30, 5.9428e-30,
         1.0000e+00, 1.3330e-27, 1.1737e-06, 3.5019e-18]])

In [281]:
pred_log = torch.log(pred)
pred_log

tensor([[-3.3545e+01, -1.7671e+01, -1.6592e+01, -3.3687e+01, -6.7963e+01,
         -6.7295e+01, -1.3113e-06, -6.1882e+01, -1.3655e+01, -4.0193e+01]])

In [282]:
y = torch.tensor([5])

## mse损失

In [283]:
F.mse_loss(logits, y)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8976\353255066.py:1: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  F.mse_loss(logits, y)


tensor(681.4020)

In [284]:
F.mse_loss(pred, y)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8976\3525572963.py:1: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  F.mse_loss(pred, y)


tensor(24.1000)

In [285]:
F.mse_loss(pred_log, y)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8976\99524341.py:1: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  F.mse_loss(pred_log, y)


tensor(2140.1594)

## 交叉熵损失

In [286]:
F.cross_entropy(logits, y)

tensor(67.2954)

In [287]:
F.cross_entropy(pred, y)

tensor(2.4611)

In [288]:
F.cross_entropy(pred_log, y)

tensor(67.2954)

# 反向传播

## 输出mse

In [289]:
x = torch.ones(1)

In [290]:
x

tensor([1.])

In [291]:
# w = torch.full([1], 2.0)
w = torch.full([1], 2.0, requires_grad=True)

In [292]:
# w.requires_grad_()

In [293]:
w

tensor([2.], requires_grad=True)

In [294]:
mse = F.mse_loss(torch.ones(1), x * w)

In [295]:
mse

tensor(1., grad_fn=<MseLossBackward0>)

In [296]:
# torch.autograd.grad(mse, [w])
torch.autograd.grad(mse, [w], retain_graph=True)

(tensor([2.]),)

In [297]:
w.grad

In [298]:
mse.backward()

In [299]:
w.grad

tensor([2.])

## 输出softmax

In [300]:
a = torch.rand(3)
a

tensor([0.7402, 0.0440, 0.5227])

In [301]:
a.requires_grad_()

tensor([0.7402, 0.0440, 0.5227], requires_grad=True)

In [302]:
p = F.softmax(a, dim=0)

In [303]:
p

tensor([0.4342, 0.2164, 0.3493], grad_fn=<SoftmaxBackward0>)

In [304]:
torch.autograd.grad(p[0], a, retain_graph=True)

(tensor([ 0.2457, -0.0940, -0.1517]),)

In [305]:
torch.autograd.grad(p[1], a, retain_graph=True)

(tensor([-0.0940,  0.1696, -0.0756]),)

In [306]:
torch.autograd.grad(p[2], a, retain_graph=True)

(tensor([-0.1517, -0.0756,  0.2273]),)

In [307]:
a.grad

In [308]:
p.shape

torch.Size([3])

In [309]:
# 以下语句会报错，因为p不是标量
p.backward(retain_graph=True)

RuntimeError: grad can be implicitly created only for scalar outputs

In [310]:
p.backward(gradient=torch.Tensor([1, 1, 1]), retain_graph=True)

In [311]:
p[0].backward(retain_graph=True)

In [312]:
a.grad

tensor([ 0.2457, -0.0940, -0.1517])

# 自动求导

In [313]:
x = torch.tensor(1.)

In [314]:
w1 = torch.tensor(2., requires_grad = True)

In [315]:
b1 = torch.tensor(1.)

In [316]:
w2 = torch.tensor(2., requires_grad = True)

In [317]:
b2 = torch.tensor(1.)

In [318]:
y1 = x * w1 + b1

In [319]:
y2 = y1 * w2 + b2

In [320]:
dy2_dy1 = torch.autograd.grad(y2, [y1], retain_graph=True)[0]
dy2_dy1

tensor(2.)

In [321]:
dy1_dw1 = torch.autograd.grad(y1, [w1], retain_graph=True)[0]
dy1_dw1

tensor(1.)

In [322]:
dy2_dw1 = torch.autograd.grad(y2, [w1], retain_graph=True)[0]
dy2_dw1

tensor(2.)

In [323]:
# 链式法则
dy2_dy1 * dy1_dw1

tensor(2.)

# 批量归一化

## BatchNorm1d

In [324]:
x = torch.randn(100, 16) + 0.5
x

tensor([[ 1.8675,  1.9806,  0.9805,  ...,  1.2771,  0.6296,  1.5349],
        [ 0.5114,  2.5285,  0.0570,  ...,  0.9811,  0.2258,  0.8736],
        [-0.3233,  1.5619,  0.3369,  ...,  0.4006,  0.0830,  0.2949],
        ...,
        [-1.0686, -0.0543,  1.2975,  ...,  0.2451,  1.5405,  1.6171],
        [ 0.8320,  0.1894, -0.1935,  ...,  0.8054, -0.0485,  0.6304],
        [ 0.2236,  1.6610,  1.2537,  ..., -1.5012,  2.4325,  0.5867]])

In [325]:
layer = torch.nn.BatchNorm1d(16)
layer.running_mean, layer.running_var

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [326]:
out = layer(x)

In [327]:
layer.running_mean, layer.running_var

(tensor([0.0592, 0.0684, 0.0568, 0.0527, 0.0351, 0.0322, 0.0477, 0.0433, 0.0475,
         0.0554, 0.0514, 0.0397, 0.0466, 0.0565, 0.0504, 0.0491]),
 tensor([0.9813, 0.9885, 1.0009, 0.9986, 1.0239, 1.0054, 0.9899, 0.9919, 0.9882,
         1.0152, 1.0001, 0.9942, 0.9946, 1.0167, 1.0032, 0.9711]))

In [328]:
out

tensor([[ 1.4219,  1.3853,  0.4125,  ...,  0.6623,  0.1241,  1.2445],
        [-0.0895,  1.9707, -0.5114,  ...,  0.3870, -0.2755,  0.4562],
        [-1.0197,  0.9378, -0.2313,  ..., -0.1530, -0.4168, -0.2335],
        ...,
        [-1.8504, -0.7893,  0.7296,  ..., -0.2976,  1.0252,  1.3425],
        [ 0.2679, -0.5289, -0.7620,  ...,  0.2235, -0.5469,  0.1664],
        [-0.4102,  1.0437,  0.6859,  ..., -1.9220,  1.9077,  0.1143]],
       grad_fn=<NativeBatchNormBackward0>)

In [329]:
x = torch.randn(100, 16) + 0.5
x

tensor([[-0.1894,  0.8917,  1.3734,  ...,  1.6801,  1.1105,  1.4125],
        [-0.7515, -0.5617,  0.3293,  ...,  0.7114, -0.5263,  1.5549],
        [ 0.2396,  0.5883,  0.7397,  ...,  0.4416, -0.3359,  1.0442],
        ...,
        [-0.4652,  0.1237,  2.8926,  ...,  0.6552,  0.9746, -0.2108],
        [ 0.2339,  0.4720,  1.3371,  ...,  0.4799,  0.3950,  0.7181],
        [ 1.2692,  1.3602,  0.7448,  ...,  0.0789,  0.0786,  1.1722]])

In [330]:
layer = torch.nn.BatchNorm1d(16)
layer.running_mean, layer.running_var

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [331]:
for i in range(100):
    out = layer(x)

In [332]:
layer.running_mean, layer.running_var

(tensor([0.5851, 0.5268, 0.5786, 0.7449, 0.6238, 0.6497, 0.3891, 0.5055, 0.5723,
         0.5089, 0.4230, 0.3449, 0.4960, 0.6784, 0.4411, 0.6644]),
 tensor([1.1663, 0.8200, 1.1400, 1.1094, 0.9198, 0.9109, 0.7415, 0.8679, 0.7836,
         0.9721, 1.1410, 0.6822, 1.0490, 0.9748, 1.0174, 0.8632]))

In [333]:
out

tensor([[-0.7208,  0.4050,  0.7480,  ...,  1.0196,  0.6670,  0.8093],
        [-1.2439, -1.2081, -0.2347,  ...,  0.0336, -0.9639,  0.9633],
        [-0.3215,  0.0683,  0.1516,  ..., -0.2410, -0.7742,  0.4109],
        ...,
        [-0.9774, -0.4474,  2.1781,  ..., -0.0236,  0.5316, -0.9468],
        [-0.3269, -0.0609,  0.7139,  ..., -0.2020, -0.0459,  0.0581],
        [ 0.6366,  0.9250,  0.1564,  ..., -0.6102, -0.3611,  0.5493]],
       grad_fn=<NativeBatchNormBackward0>)

## BatchNorm2d

In [334]:
x = torch.randn(1, 16, 7, 7)
x

tensor([[[[-8.6433e-01,  2.5760e-01, -6.0987e-01, -9.4031e-01,  5.0252e-01,
           -3.1104e+00,  9.6969e-01],
          [ 5.4721e-01, -6.0126e-02,  5.7507e-01, -7.4753e-02,  1.2376e+00,
            2.3730e+00, -3.4283e-01],
          [ 6.5160e-01, -9.8249e-02,  5.1830e-01, -3.0101e-01, -6.7043e-02,
            9.6310e-01,  2.2584e+00],
          [-1.0419e-01, -3.9921e-01, -6.7649e-01,  2.5129e-02,  5.3785e-01,
            3.4260e-02, -1.4752e+00],
          [ 2.2513e-01,  1.6955e+00, -7.5580e-01, -7.0869e-01, -3.0546e-01,
            6.3584e-01, -9.3750e-02],
          [ 7.9574e-01, -1.2708e+00,  1.0778e+00, -1.9464e-01, -4.3560e-01,
            8.8137e-01,  3.8837e-01],
          [-8.7019e-01, -3.7184e-01, -7.3647e-01,  1.3877e-01,  7.6785e-01,
           -4.0344e-01, -1.0887e+00]],

         [[ 1.1927e+00, -4.7552e-01,  1.7837e+00, -7.7612e-01,  1.7168e-01,
            3.6007e-02,  2.2103e-01],
          [ 2.6679e-01,  1.3628e+00,  1.1225e-02,  1.3406e+00,  5.4410e-01,
          

In [335]:
layer = nn.BatchNorm2d(16)
layer.running_mean, layer.running_var

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [336]:
out = layer(x)

In [337]:
layer.running_mean, layer.running_var

(tensor([ 3.4658e-03, -8.6951e-05,  3.9590e-04,  4.6162e-04, -9.0358e-03,
          1.1907e-02,  2.8666e-04,  6.9975e-03,  1.8976e-02, -7.9012e-03,
         -2.6166e-02, -5.3544e-03, -6.7695e-03, -3.8197e-04, -1.2024e-02,
         -1.3953e-02]),
 tensor([0.9900, 0.9817, 0.9700, 1.0284, 0.9922, 0.9937, 1.0122, 0.9907, 0.9870,
         0.9791, 0.9438, 1.0146, 0.9904, 0.9874, 0.9792, 0.9777]))

In [338]:
out

tensor([[[[-9.5761e-01,  2.3748e-01, -6.8656e-01, -1.0385e+00,  4.9837e-01,
           -3.3502e+00,  9.9600e-01],
          [ 5.4598e-01, -1.0096e-01,  5.7565e-01, -1.1654e-01,  1.2813e+00,
            2.4908e+00, -4.0211e-01],
          [ 6.5717e-01, -1.4157e-01,  5.1518e-01, -3.5756e-01, -1.0833e-01,
            9.8898e-01,  2.3688e+00],
          [-1.4790e-01, -4.6216e-01, -7.5752e-01, -1.0150e-02,  5.3601e-01,
           -4.2342e-04, -1.6083e+00],
          [ 2.0290e-01,  1.7691e+00, -8.4200e-01, -7.9182e-01, -3.6230e-01,
            6.4038e-01, -1.3678e-01],
          [ 8.1071e-01, -1.3906e+00,  1.1112e+00, -2.4425e-01, -5.0093e-01,
            9.0192e-01,  3.7678e-01],
          [-9.6386e-01, -4.3301e-01, -8.2141e-01,  1.1090e-01,  7.8100e-01,
           -4.6667e-01, -1.1966e+00]],

         [[ 1.3342e+00, -5.3058e-01,  1.9948e+00, -8.6661e-01,  1.9288e-01,
            4.1222e-02,  2.4805e-01],
          [ 2.9921e-01,  1.5244e+00,  1.3520e-02,  1.4996e+00,  6.0919e-01,
          