In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from torchvision import transforms

# 卷积

## 二维卷积

### 二维卷积层(nn.Conv2d)

In [13]:
x = torch.randn(1, 1, 28, 28)

In [14]:
layer = nn.Conv2d(1, 3, kernel_size=3, stride=1, padding=0)
out = layer.forward(x)
out.shape

torch.Size([1, 3, 26, 26])

In [15]:
layer = nn.Conv2d(1, 3, kernel_size=3, stride=1, padding=1)
out = layer.forward(x)
out.shape

torch.Size([1, 3, 28, 28])

In [16]:
layer = nn.Conv2d(1, 3, kernel_size=3, stride=2, padding=1)
out = layer.forward(x)
out.shape

torch.Size([1, 3, 14, 14])

In [17]:
out = layer(x)
out.shape

torch.Size([1, 3, 14, 14])

In [18]:
# 权重
layer.weight

Parameter containing:
tensor([[[[-0.2644,  0.2847,  0.2930],
          [ 0.1113,  0.2629, -0.3034],
          [ 0.1228,  0.1768,  0.1741]]],


        [[[-0.1835,  0.2314, -0.1864],
          [ 0.1513,  0.1873, -0.1763],
          [ 0.1927, -0.0050, -0.1213]]],


        [[[-0.1334,  0.2806,  0.2717],
          [-0.0815,  0.1575, -0.1269],
          [-0.0161,  0.1885, -0.1310]]]], requires_grad=True)

In [19]:
# 偏差
layer.bias

Parameter containing:
tensor([-0.2439,  0.2684,  0.2459], requires_grad=True)

In [20]:
# 评估
layer.eval()

Conv2d(1, 3, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

In [21]:
# vars返回对象的属性和属性值的字典对象
vars(layer)

{'training': False,
 '_parameters': {'weight': Parameter containing:
  tensor([[[[-0.2644,  0.2847,  0.2930],
            [ 0.1113,  0.2629, -0.3034],
            [ 0.1228,  0.1768,  0.1741]]],
  
  
          [[[-0.1835,  0.2314, -0.1864],
            [ 0.1513,  0.1873, -0.1763],
            [ 0.1927, -0.0050, -0.1213]]],
  
  
          [[[-0.1334,  0.2806,  0.2717],
            [-0.0815,  0.1575, -0.1269],
            [-0.0161,  0.1885, -0.1310]]]], requires_grad=True),
  'bias': Parameter containing:
  tensor([-0.2439,  0.2684,  0.2459], requires_grad=True)},
 '_buffers': {},
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_hooks_with_kwargs': OrderedDict(),
 '_forward_hooks_always_called': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_forward_pre_hooks_with_kwargs': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_state_dict_

### 二维卷积操作(F.Conv2d)

In [38]:
w = torch.randn(16, 3, 5, 5)
b = torch.randn(16)

In [39]:
# 以下语句会报错，因为x通道数不为3
out = F.conv2d(x, w, b, stride=1, padding=1)

RuntimeError: Given groups=1, weight of size [16, 3, 5, 5], expected input[1, 1, 28, 28] to have 3 channels, but got 1 channels instead

In [40]:
x = torch.randn(1, 3, 28, 28)

In [41]:
out = F.conv2d(x, w, b, stride=1, padding=1)
out.shape

torch.Size([1, 16, 26, 26])

In [42]:
out = F.conv2d(x, w, b, stride=2, padding=2)
out.shape

torch.Size([1, 16, 14, 14])

## 一维卷积

### 一维卷积层(nn.Conv1d)

In [28]:
# 输入张量，形状为(batch_size=1, in_channels=1, sequence_length=10)
x = torch.randn(1, 1, 10)  

In [29]:
layer = nn.Conv1d(in_channels=1, out_channels=10, kernel_size=3)

In [30]:
output = layer(x)
output.shape  

torch.Size([1, 10, 8])

### 一维卷积操作(F.conv1d)

In [31]:
# 卷积权重，形状为(out_channels=10, in_channels=1, kernel_size=3)
w = torch.randn(10, 1, 3)  

In [32]:
output = F.conv1d(x, w)
output.shape

torch.Size([1, 10, 8])

# 池化

## 最大池化

### 最大池化层(nn.MaxPool2d)

In [43]:
x = out
x.shape

torch.Size([1, 16, 14, 14])

In [44]:
layer = nn.MaxPool2d(2, stride=2)

In [45]:
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

### 最大池化操作(F.max_pool2d)

In [48]:
out = F.max_pool2d(x, 2, stride=2)
out.shape

torch.Size([1, 16, 7, 7])

## 平均池化

### 平均池化层(nn.AvgPool2d)

In [50]:
layer = nn.AvgPool2d(2, stride=2)

In [51]:
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

### 平均池化操作(F.avg_pool2d)

In [52]:
out = F.avg_pool2d(x, 2, stride=2)
out.shape

torch.Size([1, 16, 7, 7])