In [374]:
# 导包
import numpy as np
import import_ipynb
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim
from torchvision import datasets, transforms
import torchvision
from matplotlib import pyplot as plt

# 创建操作

## tensor, Tensor, IntTensor与FloatTensor

In [375]:
torch.tensor(1.3)

tensor(1.3000)

In [376]:
torch.tensor([1.1])

tensor([1.1000])

In [377]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [378]:
torch.Tensor(2, 3)

tensor([[-1.1058, -0.2031, -1.8725],
        [ 0.0371,  0.0022,  0.4779]])

In [379]:
torch.IntTensor(2, 3)

tensor([[-1136519264,         587,           0],
        [          0,           0,           0]], dtype=torch.int32)

In [380]:
torch.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float32)

## 从列表创建

In [381]:
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [382]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000], dtype=torch.float32)

In [383]:
torch.tensor([[2., 3.2], [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

## 设置默认类型

In [384]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [385]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [386]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

## full（创建具有指定形状、填充值和数据类型的张量）

In [387]:
torch.full([2, 3], 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [388]:
torch.full([], 7)

tensor(7)

In [389]:
torch.full([1], 7)

tensor([7])

## normal（创建标准分布的随机数）

In [390]:
torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0, -0.1))

tensor([-0.6718, -0.7240, -1.3722,  1.1396,  0.5346, -0.1392,  0.4404,  0.6518,
         0.0342,  0.0685])

In [391]:
torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0, -0.1))

tensor([-0.7123, -0.6807, -0.5290,  0.4313, -0.1937, -0.7874, -0.2500,  0.1201,
         0.4184, -0.0499])

## arange与range(deprecated)（范围数组）

In [392]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [393]:
torch.arange(1, 0, -0.1)

tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])

In [394]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [395]:
torch.range(0, 10)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13408\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## linspace（均分数组）与logspace（对数间隔数组）

In [396]:
torch.linspace(0, 10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [397]:
torch.linspace(0, 10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [398]:
torch.linspace(0, 10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [399]:
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [400]:
# 输出结果与torch.logspace(0, -1, steps=10)等价
10 ** (torch.linspace(0, -1, steps=10))

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [401]:
torch.logspace(0, 1, steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

In [402]:
# 输出结果与torch.logspace(0, 1, steps=10)等价
10 ** (torch.linspace(0, 1, steps=10))

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

## empty

In [403]:
torch.empty(1)

tensor([10.])

## ones（全1）, zeros（全0）与eye（对角）

In [404]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [405]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [406]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [407]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [408]:
a = torch.zeros(3, 3)

In [409]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## rand

In [410]:
torch.rand(3, 3)

tensor([[0.2750, 0.8243, 0.1779],
        [0.3458, 0.3425, 0.5669],
        [0.7354, 0.1036, 0.4110]])

In [411]:
a = torch.rand(3, 3)

## rand_like, ones_like, zeros_like

In [412]:
torch.rand_like(a)

tensor([[0.3916, 0.8007, 0.1900],
        [0.9148, 0.5078, 0.2677],
        [0.2077, 0.9748, 0.6119]])

In [413]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [414]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## randint

In [415]:
torch.randint(1, 10, [3, 3])

tensor([[7, 7, 5],
        [7, 7, 7],
        [4, 2, 8]])

## randn（创建正态分布的随机数）

In [416]:
torch.randn(3, 3)

tensor([[ 1.1839,  0.3145, -0.1978],
        [ 0.5748, -0.9419, -1.8410],
        [ 0.7784, -0.8258, -0.1839]])

## randperm（创建随机排列的整数序列）

In [417]:
a = torch.rand(2, 3)
a

tensor([[0.3303, 0.4691, 0.3560],
        [0.8693, 0.6288, 0.6288]])

In [418]:
b = torch.rand(2, 2)
b

tensor([[0.5677, 0.8430],
        [0.1225, 0.7274]])

In [419]:
# 生成一个从0到n-1的随机排列的整数序列
idx = torch.randperm(2)

In [420]:
idx

tensor([0, 1])

In [421]:
a[idx]

tensor([[0.3303, 0.4691, 0.3560],
        [0.8693, 0.6288, 0.6288]])

In [422]:
b[idx]

tensor([[0.5677, 0.8430],
        [0.1225, 0.7274]])

In [423]:
torch.randperm(10)

tensor([7, 3, 8, 6, 9, 4, 5, 1, 2, 0])

# 查看操作

In [424]:
a = torch.randn(2, 3)

## 查看Tensor的类型

In [425]:
a.dtype

torch.float64

In [426]:
a.type()

'torch.DoubleTensor'

In [427]:
type(a)

torch.Tensor

In [428]:
isinstance(a, torch.FloatTensor)

False

In [429]:
isinstance(a, torch.cuda.FloatTensor)

False

In [430]:
a = a.cuda()

In [431]:
isinstance(a, torch.cuda.FloatTensor)

False

## 查看Tensor的维度

In [432]:
a.ndim                            

2

## 查看Tensor的形状或尺寸

In [433]:
a.shape                          

torch.Size([2, 3])

In [434]:
len(a.shape)

2

In [435]:
a.size()

torch.Size([2, 3])

## 查看Tensor元素的个数

In [436]:
a.numel()

6

## 查看Tensor的梯度

In [437]:
# 没有梯度
a.grad                          

## 查看Tensor是否存储在GPU上

In [438]:
a.is_cuda                      

True

# 转换操作

## Tensor在CPU和GPU之间转换

### CPU tensor转GPU tensor

In [439]:
a.cuda()

tensor([[-0.5876, -0.7937, -0.4501],
        [-1.6437,  0.5519, -0.8420]], device='cuda:0')

### GPU tensor 转CPU tensor

In [440]:
a.cpu()

tensor([[-0.5876, -0.7937, -0.4501],
        [-1.6437,  0.5519, -0.8420]])

## Tensor在CPU和numpy之间转换

### numpy转为CPU tensor

In [441]:
numpy_test = np.array([1, 2, 3])

In [442]:
torch.from_numpy(numpy_test)

tensor([1, 2, 3])

### CPU tensor转为numpy数据

In [443]:
# 以下语句会报错，因为CUDA tensor不能直接转为numpy数据
a.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [444]:
a.cpu().numpy()

array([[-0.58757804, -0.79370454, -0.45012108],
       [-1.64374973,  0.55190247, -0.84198587]])

In [445]:
a.cpu()[0]

tensor([-0.5876, -0.7937, -0.4501])

In [446]:
a.cpu().shape

torch.Size([2, 3])

In [447]:
list(a.cpu().shape)

[2, 3]

# 选择操作

## 索引

In [448]:
a = torch.rand(4, 3, 28, 28)

In [449]:
a[0].shape, a[1].shape, a[2].shape, a[3].shape

(torch.Size([3, 28, 28]),
 torch.Size([3, 28, 28]),
 torch.Size([3, 28, 28]),
 torch.Size([3, 28, 28]))

In [450]:
a[0, 0].shape, a[0, 1].shape, a[0, 2].shape

(torch.Size([28, 28]), torch.Size([28, 28]), torch.Size([28, 28]))

In [451]:
a[0, 1, 2]

tensor([0.6815, 0.1732, 0.3649, 0.4240, 0.4304, 0.1981, 0.5793, 0.1006, 0.8919,
        0.5481, 0.1340, 0.5285, 0.3506, 0.9927, 0.7701, 0.7149, 0.2445, 0.6654,
        0.0577, 0.6466, 0.6762, 0.8486, 0.2046, 0.8071, 0.3844, 0.4364, 0.9338,
        0.5161])

## 切片

In [452]:
a.shape

torch.Size([4, 3, 28, 28])

In [453]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [454]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 28, 28])

In [455]:
a[:2, 1:, :, :].shape

torch.Size([2, 2, 28, 28])

In [456]:
a[:2, -1:, :, :].shape

torch.Size([2, 1, 28, 28])

In [457]:
a[:, :, 0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [458]:
a[:, :, ::2, ::2].shape

torch.Size([4, 3, 14, 14])

In [459]:
a[:, :, 10:20:2, 10:20:2].shape

torch.Size([4, 3, 5, 5])

## take（根据索引选择）

In [460]:
src = torch.tensor([[4, 3, 5], [6, 7, 8]])

In [461]:
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

## index_select（选择指定索引的张量）

In [462]:
a.shape

torch.Size([4, 3, 28, 28])

In [463]:
# index_select(dim, index) 
a.index_select(0, torch.tensor([1, 3])).shape

torch.Size([2, 3, 28, 28])

In [464]:
a.index_select(1, torch.tensor([0, 2])).shape

torch.Size([4, 2, 28, 28])

In [465]:
torch.arange(20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [466]:
a.index_select(2, torch.arange(20)).shape

torch.Size([4, 3, 20, 28])

In [467]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [468]:
a.shape

torch.Size([4, 3, 28, 28])

## ...（Ellipsis，省略号，不改变其他维度）

In [469]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [470]:
a[0, ...].shape

torch.Size([3, 28, 28])

In [471]:
a[:, 1, ...].shape

torch.Size([4, 28, 28])

In [472]:
a[..., :2].shape

torch.Size([4, 3, 28, 2])

## masked_select（选择满足条件的张量）

In [473]:
x = torch.randn(3, 4)
x

tensor([[-0.8539, -1.1039, -1.3049, -0.8194],
        [-1.7689, -0.7263,  0.4396,  0.0343],
        [-1.2038, -0.7567, -0.4312,  0.5721]])

In [474]:
mask = x.ge(0.5)
mask

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]])

In [475]:
torch.masked_select(x, mask)

tensor([0.5721])

In [476]:
torch.masked_select(x, mask).shape

torch.Size([1])

## where（条件筛选）

In [477]:
cond = torch.tensor([[0.6769, 0.7271],
                     [0.8884, 0.4163]])

In [478]:
a = torch.zeros(2, 2)
a

tensor([[0., 0.],
        [0., 0.]])

In [479]:
b = torch.ones(2, 2)
b

tensor([[1., 1.],
        [1., 1.]])

In [480]:
cond > 0.5

tensor([[ True,  True],
        [ True, False]])

In [481]:
torch.where(cond > 0.5, a, b)

tensor([[0., 0.],
        [0., 1.]])

## gather（收集）

In [482]:
prob = torch.rand(4, 10)
prob

tensor([[0.0576, 0.5406, 0.1173, 0.9803, 0.2431, 0.4796, 0.3533, 0.0046, 0.5292,
         0.3276],
        [0.9222, 0.2657, 0.8204, 0.6207, 0.7436, 0.8692, 0.4392, 0.8062, 0.9672,
         0.1869],
        [0.3415, 0.3175, 0.6812, 0.7068, 0.0444, 0.6185, 0.2406, 0.6421, 0.9346,
         0.5043],
        [0.0566, 0.7213, 0.6812, 0.8553, 0.4135, 0.2455, 0.1979, 0.8144, 0.8970,
         0.6631]])

In [483]:
idx = prob.topk(dim=1, k=3)

In [484]:
idx

torch.return_types.topk(
values=tensor([[0.9803, 0.5406, 0.5292],
        [0.9672, 0.9222, 0.8692],
        [0.9346, 0.7068, 0.6812],
        [0.8970, 0.8553, 0.8144]]),
indices=tensor([[3, 1, 8],
        [8, 0, 5],
        [8, 3, 2],
        [8, 3, 7]]))

In [485]:
idx[0]

tensor([[0.9803, 0.5406, 0.5292],
        [0.9672, 0.9222, 0.8692],
        [0.9346, 0.7068, 0.6812],
        [0.8970, 0.8553, 0.8144]])

In [486]:
idx[1]

tensor([[3, 1, 8],
        [8, 0, 5],
        [8, 3, 2],
        [8, 3, 7]])

In [487]:
idx = idx[1]

In [488]:
label = torch.arange(10) + 100

In [489]:
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [490]:
label.expand(4, 10)

tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [491]:
idx.long()

tensor([[3, 1, 8],
        [8, 0, 5],
        [8, 3, 2],
        [8, 3, 7]])

In [492]:
torch.gather(label.expand(4, 10), dim=1, index=idx.long())

tensor([[103, 101, 108],
        [108, 100, 105],
        [108, 103, 102],
        [108, 103, 107]])

# 维度变换操作

## view或reshape

In [493]:
a = torch.rand(4, 1, 28, 28)

In [494]:
a.shape

torch.Size([4, 1, 28, 28])

In [495]:
a.view(4, 28 * 28)

tensor([[0.1880, 0.6344, 0.8994,  ..., 0.6564, 0.6437, 0.7584],
        [0.5005, 0.4223, 0.2604,  ..., 0.7820, 0.5412, 0.0887],
        [0.0632, 0.4828, 0.9339,  ..., 0.3441, 0.6145, 0.9602],
        [0.7054, 0.6330, 0.1112,  ..., 0.1672, 0.6748, 0.2250]])

In [496]:
a.view(4, 28 * 28).shape

torch.Size([4, 784])

In [497]:
a.view(4 * 28, 28).shape

torch.Size([112, 28])

In [498]:
a.view(4, 28, 28).shape

torch.Size([4, 28, 28])

In [499]:
b = a.view(4, 784)

In [500]:
b.view(4, 28, 28, 1).shape

torch.Size([4, 28, 28, 1])

In [501]:
# 以下语句会报错，因为28*28!=783
a.view(4, 783)

RuntimeError: shape '[4, 783]' is invalid for input of size 3136

## unsqueeze（增加大小为1的维度）

In [502]:
a.shape

torch.Size([4, 1, 28, 28])

In [503]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [504]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [505]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [506]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [507]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [508]:
# 以下语句会报错，维度超出范围
a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [509]:
a = torch.tensor([1.2, 2.3])
a

tensor([1.2000, 2.3000])

In [510]:
a.shape

torch.Size([2])

In [511]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [512]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [513]:
b = torch.rand(32)
b.shape

torch.Size([32])

In [514]:
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

## squeeze（压缩大小为1的维度）

In [515]:
b.shape

torch.Size([1, 32, 1, 1])

In [516]:
b.squeeze().shape

torch.Size([32])

In [517]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [518]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [519]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [520]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

## expand（广播）

In [521]:
a = torch.rand(4, 32, 14, 14)

In [522]:
b.shape

torch.Size([1, 32, 1, 1])

In [523]:
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [524]:
b.expand(-1, 32, -1, -1).shape

torch.Size([1, 32, 1, 1])

In [525]:
b.expand(-1, 32, -1, -4).shape

torch.Size([1, 32, 1, -4])

In [526]:
c = torch.rand(1, 2)

In [527]:
c

tensor([[0.3310, 0.4445]])

In [528]:
c.expand(3, -1)

tensor([[0.3310, 0.4445],
        [0.3310, 0.4445],
        [0.3310, 0.4445]])

## repeat

In [529]:
b = torch.randn(1, 32, 1, 1)

In [530]:
b.shape

torch.Size([1, 32, 1, 1])

In [531]:
b.repeat(4, 32, 1, 1).shape

torch.Size([4, 1024, 1, 1])

In [532]:
b.repeat(4, 1, 1, 1).shape

torch.Size([4, 32, 1, 1])

In [533]:
b.repeat(4, 1, 32, 32).shape

torch.Size([4, 32, 32, 32])

## t（转置）

In [534]:
# 以下语句会报错，因为维度超出范围
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [535]:
a = torch.randn(3, 4)

In [536]:
a.t()

tensor([[ 0.8852,  1.2422, -2.1347],
        [-1.6992,  1.0840, -0.9387],
        [ 1.6018,  0.5944, -0.3059],
        [ 0.8437,  0.1979, -1.6661]])

## transpose（两两交换张量的维度）与contiguous

In [537]:
a = torch.randn(4, 3, 32, 32)

In [538]:
a.shape

torch.Size([4, 3, 32, 32])

In [539]:
a1 = a.transpose(1, 3)

In [540]:
a1.shape

torch.Size([4, 32, 32, 3])

In [541]:
a1 = a.transpose(1, 3).reshape(4, 3*32*32).reshape(4, 3, 32, 32)

In [542]:
# 以下语句会报错，因为不是连续内存，需要添加contiguous方法或者将view方法改为reshape方法
a1 = a.transpose(1, 3).view(4, 3*32*32).view(4, 3, 32, 32)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [543]:
# contiguous：返回一个连续内存的张量副本
a1 = a.transpose(1, 3).contiguous().view(4, 3*32*32).view(4, 3, 32, 32)

In [544]:
a2 = a.transpose(1, 3).contiguous().view(4, 3*32*32).view(4, 32, 32, 3).transpose(1, 3)

In [545]:
a.shape, a1.shape, a2.shape

(torch.Size([4, 3, 32, 32]),
 torch.Size([4, 3, 32, 32]),
 torch.Size([4, 3, 32, 32]))

In [546]:
torch.eq(a, a1)

tensor([[[[ True, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False,

In [547]:
torch.all(torch.eq(a, a1))

tensor(False)

In [548]:
torch.eq(a, a2)

tensor([[[[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ...

In [549]:
torch.all(torch.eq(a, a2))

tensor(True)

## permute（重新排列张量的维度）

In [550]:
a = torch.rand(4, 3, 28, 28)

In [551]:
a.transpose(1, 3).shape

torch.Size([4, 28, 28, 3])

In [552]:
b = torch.rand(4, 3, 28, 32)

In [553]:
b.transpose(1, 3).shape

torch.Size([4, 32, 28, 3])

In [554]:
b.transpose(1, 3).transpose(1, 2).shape

torch.Size([4, 28, 32, 3])

In [555]:
b.permute(0, 2, 3, 1).shape

torch.Size([4, 28, 32, 3])

## Broadcast（自动广播）

In [556]:
a = torch.rand(4, 32, 14, 14)

In [557]:
(a + 5.0).shape

torch.Size([4, 32, 14, 14])

In [558]:
b = torch.rand(1, 32, 1, 1)

In [559]:
(a + b).shape

torch.Size([4, 32, 14, 14])

In [560]:
a = torch.rand(4, 32, 14, 14)

In [561]:
b = torch.rand(14, 14)

In [562]:
(a + b).shape

torch.Size([4, 32, 14, 14])

In [563]:
a = torch.rand(4, 32, 14, 14)

In [564]:
b = torch.rand(2, 32, 14, 14)

In [565]:
# 以下语句会报错，因为不满足自动广播的条件
(a + b).shape

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

In [566]:
a = torch.rand(4, 3, 32, 32)

In [567]:
b = torch.rand(32, 32)

In [568]:
(a + b).shape

torch.Size([4, 3, 32, 32])

In [569]:
b = torch.rand(3, 1, 1)

In [570]:
(a + b).shape

torch.Size([4, 3, 32, 32])

In [571]:
b = torch.rand(1, 1, 1, 1)

In [572]:
(a + b).shape

torch.Size([4, 3, 32, 32])

In [573]:
a = torch.randn(4, 32, 14, 14)
b = torch.randn(1, 32, 14, 14)
a + b

tensor([[[[ 1.5918e+00, -9.1276e-01, -1.0572e+00,  ..., -1.5902e+00,
            1.5675e+00, -3.0014e-01],
          [-4.1147e-01,  1.2097e-01,  1.1191e+00,  ...,  1.8585e+00,
           -1.8740e+00,  1.4371e+00],
          [ 3.4123e+00, -2.7159e+00, -7.7433e-01,  ...,  5.2555e-01,
           -4.1984e-01, -4.6692e-01],
          ...,
          [ 3.7377e-01, -1.2611e+00,  1.1759e+00,  ..., -2.0061e+00,
           -1.5055e+00, -1.0576e+00],
          [-5.7912e-01,  2.0296e+00, -1.5863e+00,  ...,  6.2675e-01,
            2.1566e+00, -1.0203e+00],
          [-9.4397e-01, -4.5876e-01,  1.1613e+00,  ..., -2.5645e+00,
           -3.5190e+00,  4.5296e-02]],

         [[-1.2100e+00, -1.2299e+00, -6.5159e-01,  ...,  2.9741e+00,
            2.5350e-01, -1.4053e+00],
          [ 2.0592e+00,  6.4845e-01,  7.1910e-02,  ..., -1.6886e+00,
           -3.0242e+00,  1.0640e+00],
          [-2.1995e+00,  1.1773e+00, -4.1358e-01,  ...,  2.1368e+00,
           -1.5065e+00, -1.8433e+00],
          ...,
     

## F.interpolate（下/上采样）

In [574]:
x = torch.randn(1, 3, 28, 28)
x.shape

torch.Size([1, 3, 28, 28])

In [575]:
out = F.interpolate(x, scale_factor=2, mode='nearest')
out.shape

torch.Size([1, 3, 56, 56])

In [576]:
out = F.interpolate(x, scale_factor=3, mode='nearest')
out.shape

torch.Size([1, 3, 84, 84])

# 算术运算

## 乘法

### 运算符*（逐元素乘）

In [577]:
a = torch.ones([2, 2]) * 3

In [578]:
a

tensor([[3., 3.],
        [3., 3.]])

In [579]:
b = torch.ones([2, 2])

In [580]:
b

tensor([[1., 1.],
        [1., 1.]])

In [581]:
a * b

tensor([[3., 3.],
        [3., 3.]])

### mul（逐元素乘）

In [582]:
torch.mul(a, b)

tensor([[3., 3.],
        [3., 3.]])

### mm（二维乘）

In [583]:
torch.mm(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [584]:
a = torch.rand(4, 3, 28, 64)

In [585]:
b = torch.rand(4, 3, 64, 32)

In [586]:
# 以下语句会报错，因为不是二维矩阵
torch.mm(a, b)

RuntimeError: self must be a matrix

### bmm（三维带batch的矩阵乘法）

In [587]:
a = torch.rand(4, 28, 64)

In [588]:
b = torch.rand(4, 64, 28)

In [589]:
torch.bmm(a, b).shape

torch.Size([4, 28, 28])

### matmul（多维乘）

In [590]:
torch.matmul(a, b)

tensor([[[18.8244, 16.6040, 19.3866,  ..., 16.9298, 17.4349, 18.7379],
         [14.3240, 13.9354, 15.9174,  ..., 13.4941, 13.6587, 15.7357],
         [18.4139, 16.9579, 18.7171,  ..., 16.2763, 17.3621, 18.3540],
         ...,
         [17.5608, 16.3314, 19.5603,  ..., 16.6973, 15.7249, 18.9331],
         [17.6832, 15.5344, 18.6889,  ..., 15.4917, 14.6570, 17.2341],
         [16.9216, 15.1950, 17.2440,  ..., 14.8149, 13.5052, 16.8501]],

        [[17.9589, 17.0600, 13.5480,  ..., 16.7421, 14.4874, 17.3890],
         [17.6886, 15.8802, 14.3909,  ..., 16.5133, 14.7420, 15.2856],
         [17.3812, 15.7007, 13.1730,  ..., 15.2073, 13.5019, 16.0716],
         ...,
         [17.4935, 14.4137, 14.3565,  ..., 15.7995, 13.4235, 15.2223],
         [17.6749, 15.6465, 15.1062,  ..., 17.2423, 15.1139, 16.9194],
         [18.6063, 15.6097, 14.0870,  ..., 16.7315, 15.5371, 16.8444]],

        [[19.8911, 17.6193, 16.2931,  ..., 16.9950, 18.6973, 16.6616],
         [14.0353, 12.5647, 13.6787,  ..., 13

In [591]:
torch.matmul(a, b).shape

torch.Size([4, 28, 28])

In [592]:
b = torch.rand(4, 1, 64, 32)

In [593]:
torch.matmul(a, b).shape

torch.Size([4, 4, 28, 32])

### @（任意维乘）

In [594]:
x = torch.rand(4, 784)

In [595]:
w = torch.rand(512, 784)

In [596]:
(x@w.t()).shape

torch.Size([4, 512])

## add(+), sub(-)与div(/)

In [597]:
a = torch.rand(3, 4)

In [598]:
a

tensor([[0.2315, 0.0988, 0.2261, 0.0284],
        [0.1885, 0.4454, 0.4499, 0.1001],
        [0.8782, 0.9185, 0.6589, 0.0934]])

In [599]:
b = torch.rand(4)

In [600]:
b

tensor([0.4719, 0.9271, 0.5333, 0.3220])

In [601]:
a + b

tensor([[0.7034, 1.0259, 0.7593, 0.3504],
        [0.6604, 1.3725, 0.9832, 0.4221],
        [1.3502, 1.8456, 1.1922, 0.4154]])

In [602]:
torch.add(a, b)

tensor([[0.7034, 1.0259, 0.7593, 0.3504],
        [0.6604, 1.3725, 0.9832, 0.4221],
        [1.3502, 1.8456, 1.1922, 0.4154]])

In [603]:
a - b

tensor([[-0.2404, -0.8283, -0.3072, -0.2936],
        [-0.2834, -0.4817, -0.0833, -0.2219],
        [ 0.4063, -0.0086,  0.1257, -0.2287]])

In [604]:
torch.sub(a, b)

tensor([[-0.2404, -0.8283, -0.3072, -0.2936],
        [-0.2834, -0.4817, -0.0833, -0.2219],
        [ 0.4063, -0.0086,  0.1257, -0.2287]])

In [605]:
a / b

tensor([[0.4906, 0.1066, 0.4240, 0.0881],
        [0.3994, 0.4804, 0.8437, 0.3108],
        [1.8609, 0.9907, 1.2356, 0.2900]])

In [606]:
torch.div(a, b)

tensor([[0.4906, 0.1066, 0.4240, 0.0881],
        [0.3994, 0.4804, 0.8437, 0.3108],
        [1.8609, 0.9907, 1.2356, 0.2900]])

## pow(**), sqrt与rsqrt

In [607]:
a = torch.full([2, 2], 3)

In [608]:
a

tensor([[3, 3],
        [3, 3]])

In [609]:
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [610]:
a**2

tensor([[9, 9],
        [9, 9]])

In [611]:
aa = a**2

In [612]:
aa

tensor([[9, 9],
        [9, 9]])

In [613]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [614]:
# 平方根的倒数
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [615]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

## exp 

In [616]:
# e约为2.71828
a = torch.exp(torch.ones(2, 2))

In [617]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

## log

In [618]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

## floor, ceil, trunc（取整数）, frac（取小数）与round

In [619]:
a = torch.tensor(3.14)

In [620]:
# trunc: 取整数部分
# frac: 取小数部分
# round: 舍入到最近的整数
a.floor(), a.ceil(), a.trunc(), a.frac(), a.round()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400), tensor(3.))

## clamp（将张量中的元素限制在一个指定的范围内）

In [621]:
grad = torch.rand(2, 3) * 15

In [622]:
grad.max()

tensor(12.9646)

In [623]:
grad.median()

tensor(5.1831)

In [624]:
# 将输入张量的每个元素夹紧到区间[min, max]
grad.clamp(10)

tensor([[10.0000, 10.0000, 10.0000],
        [10.0000, 12.9646, 10.0000]])

In [625]:
grad

tensor([[ 5.8666,  5.0438,  4.9563],
        [ 6.0884, 12.9646,  5.1831]])

In [626]:
grad.clamp(0, 10)

tensor([[ 5.8666,  5.0438,  4.9563],
        [ 6.0884, 10.0000,  5.1831]])

# 关系运算

## gt(>), ge(>=), lt(<), le(<=)

In [627]:
a = torch.randn(2, 3)
a

tensor([[ 0.0907, -1.2705, -0.2124],
        [ 1.5578,  1.3154, -0.5008]])

In [628]:
a > 0

tensor([[ True, False, False],
        [ True,  True, False]])

In [629]:
torch.gt(a, 0)

tensor([[ True, False, False],
        [ True,  True, False]])

In [630]:
a >= 0

tensor([[ True, False, False],
        [ True,  True, False]])

In [631]:
torch.ge(a, 0)

tensor([[ True, False, False],
        [ True,  True, False]])

In [632]:
a < 0

tensor([[False,  True,  True],
        [False, False,  True]])

In [633]:
torch.lt(a, 0)

tensor([[False,  True,  True],
        [False, False,  True]])

In [634]:
a <= 0

tensor([[False,  True,  True],
        [False, False,  True]])

In [635]:
torch.le(a, 0)

tensor([[False,  True,  True],
        [False, False,  True]])

## ne(!=), eq(==)与equal

In [636]:
a != 0

tensor([[True, True, True],
        [True, True, True]])

In [637]:
torch.ne(a, 0)

tensor([[True, True, True],
        [True, True, True]])

In [638]:
a == 0

tensor([[False, False, False],
        [False, False, False]])

In [639]:
torch.eq(a, 0)

tensor([[False, False, False],
        [False, False, False]])

In [640]:
a = torch.ones(2, 3)

In [641]:
b = torch.randn(2, 3)

In [642]:
torch.eq(a, b)

tensor([[False, False, False],
        [False, False, False]])

In [643]:
torch.eq(a, a)

tensor([[True, True, True],
        [True, True, True]])

In [644]:
torch.equal(a, a)

True

## all

In [645]:
torch.all(torch.eq(a + b, torch.add(a, b)))

tensor(True)

In [646]:
torch.all(torch.eq(a - b, torch.sub(a, b)))

tensor(True)

In [647]:
torch.all(torch.eq(a * b, torch.mul(a, b)))

tensor(True)

In [648]:
torch.all(torch.eq(a / b, torch.div(a, b)))

tensor(True)

# 逻辑运算

## logical_and

In [649]:
c = torch.tensor([True, False, True])
d = torch.tensor([True, True, False])
torch.logical_and(c, d)

tensor([ True, False, False])

## logical_or

In [650]:
torch.logical_or(c, d)

tensor([True, True, True])

## logical_not

In [651]:
torch.logical_not(c)

tensor([False,  True, False])

## logical_xor

In [652]:
torch.logical_xor(c, d)

tensor([False,  True,  True])

# 拼接与拆分操作

## cat（concatence，拼接）

In [653]:
a = torch.rand(4, 32, 8)

In [654]:
b = torch.rand(5, 32, 8)

In [655]:
torch.cat([a, b], dim = 0).shape

torch.Size([9, 32, 8])

In [656]:
a1 = torch.rand(4, 3, 32, 32)

In [657]:
a2 = torch.rand(5, 3, 32, 32)

In [658]:
torch.cat([a1, a2], dim=0).shape

torch.Size([9, 3, 32, 32])

In [659]:
a2 = torch.rand(4, 1, 32, 32)

In [660]:
# 以下语句会报错，因为不满足cat的条件
torch.cat([a1, a2], dim=0).shape

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 1 for tensor number 1 in the list.

In [661]:
torch.cat([a1, a2], dim=1).shape

torch.Size([4, 4, 32, 32])

In [662]:
a1 = torch.rand(4, 3, 16, 32)

In [663]:
a2 = torch.rand(4, 3, 16, 32)

In [664]:
torch.cat([a1, a2], dim = 2).shape

torch.Size([4, 3, 32, 32])

## stack（堆叠）

In [665]:
a = torch.randn(4, 3, 16, 32)

In [666]:
torch.cat([a, a], dim=2).shape

torch.Size([4, 3, 32, 32])

In [667]:
torch.stack([a, a, a, a], dim=2).shape

torch.Size([4, 3, 4, 16, 32])

In [668]:
a = torch.rand(32, 8)

In [669]:
b = torch.rand(32, 8)

In [670]:
torch.stack([a, b], dim=0).shape

torch.Size([2, 32, 8])

In [671]:
a.shape

torch.Size([32, 8])

In [672]:
b = torch.rand(30, 8)

In [673]:
# 以下语句会报错，因为不满足stack的条件
torch.stack([a, b], dim=0).shape

RuntimeError: stack expects each tensor to be equal size, but got [32, 8] at entry 0 and [30, 8] at entry 1

In [674]:
torch.cat([a, b], dim=0).shape

torch.Size([62, 8])

## split（根据长度拆分）

In [675]:
b = torch.rand(32, 8)

In [676]:
a.shape

torch.Size([32, 8])

In [677]:
c = torch.stack([a, b], dim=0)

In [678]:
c.shape

torch.Size([2, 32, 8])

In [679]:
c = torch.randn(4, 32, 8)

In [680]:
c.shape

torch.Size([4, 32, 8])

In [681]:
aa, bb = c.split(2, dim=0)

In [682]:
aa.shape, bb.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

In [683]:
# 以下语句会报错，因为不满足split的条件
aa, bb = c.split(1, dim=0)

ValueError: too many values to unpack (expected 2)

In [684]:
aa.shape, bb.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

In [685]:
aa, bb = c.split(2, dim=0)

In [686]:
# 以下语句会报错，因为不满足split的条件
aa, bb = c.split([0, 2], dim=0)

RuntimeError: split_with_sizes expects split_sizes to sum exactly to 4 (input tensor's size at dimension 0), but got split_sizes=[0, 2]

In [687]:
aa.shape, bb.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

## chunk（根据数量拆分）

In [688]:
b = torch.rand(32, 8)

In [689]:
a.shape

torch.Size([32, 8])

In [690]:
c = torch.stack([a, b], dim=0)

In [691]:
c = torch.randn(2, 32, 8)

In [692]:
c.shape

torch.Size([2, 32, 8])

In [693]:
aa, bb = c.chunk(2, dim=0)

In [694]:
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

# 统计操作

## min, max, mean, median（中位数）, sum（元素和）与prod（元素积）

In [695]:
torch.arange(8)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [696]:
a = torch.arange(8).view(2, 4).float()

In [697]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=torch.float32)

In [698]:
a.min(), a.max(), a.mean(), a.median(), a.sum(), a.prod()

(tensor(0., dtype=torch.float32),
 tensor(7., dtype=torch.float32),
 tensor(3.5000, dtype=torch.float32),
 tensor(3., dtype=torch.float32),
 tensor(28., dtype=torch.float32),
 tensor(0., dtype=torch.float32))

## argmax（最大值的索引）与argmin（最小值的索引）

In [699]:
a.argmax(), a.argmin()

(tensor(7), tensor(0))

In [700]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=torch.float32)

In [701]:
a = a.view(1, 2, 4)

In [702]:
a.argmax()

tensor(7)

In [703]:
a.argmin()

tensor(0)

In [704]:
a = torch.rand(2, 3, 4)

In [705]:
a.argmax(), a.argmin()

(tensor(0), tensor(1))

In [706]:
a = torch.randn(4, 10)

In [707]:
a

tensor([[-1.2356,  0.6874, -1.3478, -1.3104, -0.9571, -1.8671, -0.5941,  0.5568,
         -1.3134, -0.0877],
        [-0.7692,  0.5214, -0.5936,  0.8442,  0.7307,  0.1262,  0.5050, -0.4720,
         -1.5647, -1.6788],
        [-0.4388, -0.2661, -1.2882,  0.9870, -2.6292, -0.4162, -1.3685,  0.0824,
          0.1719,  0.7527],
        [ 1.1052,  1.1558, -0.0644, -0.0294,  0.9656,  0.8240, -1.2425,  1.6834,
         -0.5566, -0.2451]])

In [708]:
a[0]

tensor([-1.2356,  0.6874, -1.3478, -1.3104, -0.9571, -1.8671, -0.5941,  0.5568,
        -1.3134, -0.0877])

In [709]:
a.argmax()

tensor(37)

In [710]:
a.argmax(dim=1)

tensor([1, 3, 3, 7])

In [711]:
a.argmax(dim=0)

tensor([3, 3, 3, 2, 3, 3, 1, 3, 2, 2])

In [712]:
a.argmin(dim=1)

tensor([5, 9, 4, 6])

In [713]:
a.argmin(dim=0)

tensor([0, 2, 0, 0, 2, 0, 2, 1, 1, 1])

## dim（dimension，维度）与keepdim

In [714]:
a

tensor([[-1.2356,  0.6874, -1.3478, -1.3104, -0.9571, -1.8671, -0.5941,  0.5568,
         -1.3134, -0.0877],
        [-0.7692,  0.5214, -0.5936,  0.8442,  0.7307,  0.1262,  0.5050, -0.4720,
         -1.5647, -1.6788],
        [-0.4388, -0.2661, -1.2882,  0.9870, -2.6292, -0.4162, -1.3685,  0.0824,
          0.1719,  0.7527],
        [ 1.1052,  1.1558, -0.0644, -0.0294,  0.9656,  0.8240, -1.2425,  1.6834,
         -0.5566, -0.2451]])

In [715]:
a.max(dim=1)

torch.return_types.max(
values=tensor([0.6874, 0.8442, 0.9870, 1.6834]),
indices=tensor([1, 3, 3, 7]))

In [716]:
a.argmax(dim=1)

tensor([1, 3, 3, 7])

In [717]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[0.6874],
        [0.8442],
        [0.9870],
        [1.6834]]),
indices=tensor([[1],
        [3],
        [3],
        [7]]))

In [718]:
a.argmax(dim=1, keepdim=True)

tensor([[1],
        [3],
        [3],
        [7]])

## topk

In [719]:
a

tensor([[-1.2356,  0.6874, -1.3478, -1.3104, -0.9571, -1.8671, -0.5941,  0.5568,
         -1.3134, -0.0877],
        [-0.7692,  0.5214, -0.5936,  0.8442,  0.7307,  0.1262,  0.5050, -0.4720,
         -1.5647, -1.6788],
        [-0.4388, -0.2661, -1.2882,  0.9870, -2.6292, -0.4162, -1.3685,  0.0824,
          0.1719,  0.7527],
        [ 1.1052,  1.1558, -0.0644, -0.0294,  0.9656,  0.8240, -1.2425,  1.6834,
         -0.5566, -0.2451]])

In [720]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[ 0.6874,  0.5568, -0.0877],
        [ 0.8442,  0.7307,  0.5214],
        [ 0.9870,  0.7527,  0.1719],
        [ 1.6834,  1.1558,  1.1052]]),
indices=tensor([[1, 7, 9],
        [3, 4, 1],
        [3, 9, 8],
        [7, 1, 0]]))

In [721]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-1.8671, -1.3478, -1.3134],
        [-1.6788, -1.5647, -0.7692],
        [-2.6292, -1.3685, -1.2882],
        [-1.2425, -0.5566, -0.2451]]),
indices=tensor([[5, 2, 8],
        [9, 8, 0],
        [4, 6, 2],
        [6, 8, 9]]))

## kthvalue

In [722]:
a

tensor([[-1.2356,  0.6874, -1.3478, -1.3104, -0.9571, -1.8671, -0.5941,  0.5568,
         -1.3134, -0.0877],
        [-0.7692,  0.5214, -0.5936,  0.8442,  0.7307,  0.1262,  0.5050, -0.4720,
         -1.5647, -1.6788],
        [-0.4388, -0.2661, -1.2882,  0.9870, -2.6292, -0.4162, -1.3685,  0.0824,
          0.1719,  0.7527],
        [ 1.1052,  1.1558, -0.0644, -0.0294,  0.9656,  0.8240, -1.2425,  1.6834,
         -0.5566, -0.2451]])

In [723]:
# kthvalue函数用于返回输入张量在指定维度上的第k个最小值及其索引
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([-0.0877,  0.5214,  0.1719,  1.1052]),
indices=tensor([9, 1, 8, 0]))

In [724]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([-1.3134, -0.7692, -1.2882, -0.2451]),
indices=tensor([8, 0, 2, 9]))

In [725]:
a.kthvalue(3, dim=1)

torch.return_types.kthvalue(
values=tensor([-1.3134, -0.7692, -1.2882, -0.2451]),
indices=tensor([8, 0, 2, 9]))

## norm（范数）

In [726]:
a = torch.full([8], 1.0)

In [727]:
b = a.view(2, 4)

In [728]:
c = a.view(2, 2, 2)

In [729]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [730]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [731]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [732]:
# 范数1：绝对值求和 
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [733]:
# 范数2：平方和开根号
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [734]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [735]:
b.norm(1, dim=1)

tensor([4., 4.])

In [736]:
b.norm(2, dim=1)

tensor([2., 2.])

In [737]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [738]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [739]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])